apiVersion: v1
kind: Service
metadata:
  name: rstudio-service
  namespace: rstudio
spec:
  type: ClusterIP
  ports:
  - port: 8787
    targetPort: 8787
    protocol: TCP
    name: http
  selector:
    app: rstudio